#!/usr/bin/env python3
"""
Brief description of the subcommand.

Additional information about subcommand.
"""

import sys

import cmdutil


class `SubcommandName`(cmdutil.Subcommand):

    # def configure_parser(self, parser):
    #     pass

    # def validate_arguments(self):
    #     pass

    def execute(self):
        print(self.arguments)


if __name__ == "__main__":
    `SubcommandName`().run(sys.argv)
